### ISSUE TITLE
关于数据处理的问题

### ISSUE THREAD

**Issue by xuekanhua** [hulkima/PDRec#2]
1. 请问使用的数据集是Amazon2023还是Amazon2018，以及数据集的其他信息这一部分好像在论文中没有详细说明。
2. 请问能否告知数据处理的方式，或将数据处理代码开源？

**Comment by hulkima** [comment]
Sorry for the late reply. As for the Point 1,  Amazon_2023 dataset had not yet been released when we were working on PDRec, so we were still using the Amazon_2018 dataset. And for the Point 2, to demonstrate the universality of PDRec in CDR, we randomly select the users that have behaviors in both two domains from the same platform, filter them with the three-core setting in each dataset, and treat all reviews as positive feedback. You can view some of the pre-process files in this Google Drive link: https://drive.google.com/drive/folders/1uhw-EjtADGkNQbiGKbMsIUGWxPTvV0XU?usp=drive_link

**Comment by xuekanhua** [comment]
Thank you for your answer and thank you very much for the data processing program you provided.
